### ISSUE TITLE
Create the thread scraper 

### ISSUE THREAD

**Issue by eLopez6** [Susanou/EECS349FinalProject#2]
This is contingent on #1 ,

This scraper should be able to take a URL or some thread ID and download the HTML for the forum (probably using BeautifulSoup). 
With the HTML handled, it should be able to distinguish comments from each other and collect all the necessary information (as specified in the T1 template). 

However, this is separate from the sentiment analysis  (good review, question, etc)

**Comment by Susanou** [comment]
Yeah BeautifulSoup should be able to distinguish between different comments. Here is a link to the documentation on it https://www.crummy.com/software/BeautifulSoup/bs4/doc/

**Comment by eLopez6** [comment]
Whoever takes this, begin writing and assume that you will get the HTML correctly. 

My Forumscraper section is working on generating the thread ids, which we will request with all the necessary cookies to get the HTML for scraping.

**Comment by eLopez6** [comment]
Building on Anthony's work. Validating my changes now.
