### ISSUE TITLE
Analyze the sentiment of the comments

### ISSUE THREAD

**Issue by eLopez6** [Susanou/EECS349FinalProject#4]

**Comment by Susanou** [comment]
To use the AI, there are three things you need to download:
1. Git LFS (the file sizes for the AIs are enormous for Github)
2. joblib to unpack the files in python code

**Comment by eLopez6** [comment]
Great work. If you have other homework to do, go ahead and chill for now. I have some errands today, but I'll get to figuring out the scraping tonight and tomorrow.
